# Generated by Django 4.2.1 on 2023-05-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='level',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='tree_id',
        ),
    ]
