# Generated by Django 4.2.1 on 2023-05-26 13:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import etest.models


class Migration(migrations.Migration):

    dependencies = [
        ('etest', '0002_alter_appuser_managers_remove_appuser_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioData',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='etest.basemodel')),
                ('audio_file', models.FileField(upload_to=etest.models.upload_location_audio)),
                ('create_at', models.DateField(default=datetime.datetime(2023, 5, 26, 18, 31, 13, 570927))),
                ('user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etest.appuser')),
            ],
            bases=('etest.basemodel',),
        ),
    ]
