# Generated by Django 4.2.1 on 2023-05-31 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etest', '0003_audiodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='input_user_name',
            field=models.CharField(default='aa', max_length=255),
        ),
        migrations.AlterField(
            model_name='audiodata',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2023, 5, 31, 14, 24, 44, 742293)),
        ),
    ]
